### ISSUE TITLE
Kiwi crops video

### ISSUE THREAD

**Issue by SylwesterDu** [kiwibrowser/src.next#477] opened 2022-01-08 12:58 UTC
When fullscreen, left side of video is cropped about 5%

**To Reproduce**
Open the same video in kiwi and other browser. 

**Smartphone (please complete the following information):**
 - Device: [Redmi note 10s]
 - Android Version : [11 ]
 - Kiwi Browser Version [98.0.4758.29]

First screenshot is from brave, second from kiwi

![Screenshot_2022-01-08-14-02-05-881_com.brave.browser.jpg](https://user-images.githubusercontent.com/61783625/148645196-75b1ebe6-5dac-4bc4-9a1e-ed283ddf58f1.jpg)
![Screenshot_2022-01-08-14-01-36-757_com.kiwibrowser.browser.jpg](https://user-images.githubusercontent.com/61783625/148645206-f80cf1bb-2424-4c52-b970-13cd4195ebfe.jpg)

**Comment by karl-pae** [comment] 2022-03-17 09:12
Duplicate of#256. Close.

**Closed** 2023-09-01 18:36 UTC
Labels: bug
