### ISSUE TITLE
[BUG] No Undo Button

### ISSUE THREAD

**Issue by StreamerMLG** [kiwibrowser/src.next#179] opened 2021-07-25 04:49 UTC
Version: 93.0.4577.11 (457701115)

When you remove a tab it doesn't show up fix it please because sometimes it's annoying because I accidentally remove a tab and cannot go back thank you.

**Comment by Lartsch** [comment] 2021-07-25 10:35
Which tab view are you using? I'm using the grid layout and still get the "Undo" bar @StreamerMLG

**Comment by s1710335** [comment] 2021-07-25 10:45
I am the same person as #183.
I'm using the old("original") Tab view and have a similar situation.
Also, the toolbar is located at the top.

**Comment by Lartsch** [comment] 2021-07-25 10:49
Okay, I can confirm that ONLY with the "Original" tab style. Others are working fine. So this is an actual bug.
@s1710335 Would you mind closing your other issue to help keep this repo tidy? :)

**Comment by s1710335** [comment] 2021-07-25 10:55
I understand. I'm sorry.

**Comment by Lartsch** [comment] 2021-07-25 10:56
@s1710335 No worries! Thank you :)

**Comment by StreamerMLG** [comment] 2021-07-26 02:35
> Okay, I can confirm that ONLY with the "Original" tab style no "Undo" button appears. Others are working fine. So this is an actual bug.
> @s1710335 Would you mind closing your other issue to help keep this repo tidy? :)

Yes i can confirm this default and original doesn't show undo button. Hope to get this fix in next version.

**Comment by kiwibrowser** [comment] 2021-07-26 02:38
Triage: affects original and horizontal due to crash in UndoController

**Comment by StreamerMLG** [comment] 2021-07-26 04:23
> Triage: affects original and horizontal due to crash in UndoController

Soo it's literally a bug thank you.

**Comment by kiwibrowser** [comment] 2021-07-26 14:24
Fixed in upcoming build

**Closed** 2021-08-07 03:08 UTC
Labels: bug
