### ISSUE TITLE
Selection magnifier displaced and shows wrong content

### ISSUE THREAD

**Issue by andruska** [kiwibrowser/src.next#254] opened 2021-08-03 13:25 UTC
While the bottom toolbar is visible, moving the handles of the selection, the magnifier window still covers the selected text and shows the wrong content. 

The issue #170 is still partly fixed.

**Comment by Lartsch** [comment] 2021-08-03 17:06
Duplicate of #170. Please close @andruska

**Comment by Lartsch** [comment] 2021-08-03 17:11
Duplicate of #190. Please close @andruska

**Closed** 2021-08-04 12:35 UTC
Labels: bug
