### ISSUE TITLE
Undo close tab missing

### ISSUE THREAD

**Issue by fredgolightly** [kiwibrowser/src.next#828] opened 2023-03-19 19:47 UTC
**Describe the bug**
I've update from October 2022 version to March 18th.
Now, after closing a tab, by mistake or not, there's no 'undo close tab' prompt

**To Reproduce**
Close a tab

**Expected behavior**
An 'undo' closed tab popup appears

**Screenshots**
Lack of feature makes this impossible to capture

**Smartphone (please complete the following information):**
 - Device: Pixel 5, Tab S8
 - Android Version : 13
 - Kiwi Browser Version: 111.0.5363.78

**Additional context**

**Comment by MooShuOrc** [comment] 2023-04-03 20:03
Confirmed. Note that this may be intentional since there's still a Recent Tabs menu item which makes the Undo popup unnecessary (but still handy).

**Comment by fblancoros** [comment] 2023-04-11 20:25
I miss that feature too. It was super handy.

**Comment by d3ward** [comment] 2023-07-17 20:08
Kiwi v116 ( Github release ) now have this feature. When closing a tab , popup to undo is available.

**Closed by d3ward** 2023-07-17 20:08 UTC
Labels: bug
