### ISSUE TITLE
refresh home page - news

### ISSUE THREAD

**Issue by Titanposeidon** [kiwibrowser/src.next#536] opened 2022-03-08 15:38 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
 home page , news dont refresh when pull down the page, it'd be nice to add this feature

**Additional context**

**Comment by karl-pae** [comment] 2022-03-10 15:24
Until this gets implemented (maybe), you can use refresh button from the menu. :)

**Comment by karl-pae** [comment] 2022-03-10 15:29
Duplicate of #518.
**close.**

**Comment by karl-pae** [comment] 2022-03-17 06:19
You can't swipe down (pull to refresh) or 

You can swipe down, but news feed won't refresh.

**Comment by karl-pae** [comment] 2022-03-17 06:20
Hi, download the latest build from here:
https://github.com/kiwibrowser/src.next/releases

and revert if the issue still occurs, else you can close this issue.

I don't have that problem. Swipe down works and news feed too is refresh. 😕

**Comment by kiwibrowser** [comment] 2022-03-17 06:37
Freshly fixed in 99-series :) Thank you very much @karl-pae for triage and feedback!

**Closed by kiwibrowser** 2022-03-17 06:37 UTC
Labels: enhancement

**Comment by karl-pae** [comment] 2022-03-17 06:41
> Freshly fixed in 99-series :) Thank you very much @karl-pae for triage and feedback!

So #518 too should be closed. 😄
