### ISSUE TITLE
There is no empty button in the address bar.

### ISSUE THREAD

**Issue by drc5521** [kiwibrowser/src.next#592] opened 2022-04-18 08:54 UTC
**Describe the bug**
There is no empty button(p2) in the address bar.

**To Reproduce**

**Expected behavior**
The empty button appears every time.

**Screenshots**
p1
![Screenshot_20220418_164510_com kiwibrowser browser_edit_24982576577437](https://user-images.githubusercontent.com/55195642/163783161-41677352-49af-443f-9e89-741f83898d03.png)
p2
![Screenshot_20220418_165403_com kiwibrowser browser](https://user-images.githubusercontent.com/55195642/163783856-9e785df8-da3f-4bff-bb17-822899784cab.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 7]HONOR X10
 - Android Version : [e.g. A11 ]A10
 - Kiwi Browser Version [ e.g. 90.0.4577.17 ]last release

**Additional context**

**Comment by Ibuprophen** [comment] 2022-04-18 15:50
I 2nd this... 

I had just recently realized that the "×" option (to the very right of the URL bar), that would  clear the existing URL populated, is no longer available. 

I also have the most recent pre-release apk installed. 

I even disabled the few chrome extensions I have and restarted the browser. 

I also thought that it might have been there, but not viewable (at first), but that wasn't the case here. 

I just wanted to provide all the information & steps I took so you can see where I'm at with this bug. 

I also have the ARM version of the Apk on my device. 

Thanks a Bunch! :-) 

~Ibuprophen

**Comment by netrunner-exe** [comment] 2022-04-18 20:21
Duplicate of #586

**Comment by Ibuprophen** [comment] 2022-04-19 15:53
@drc5521 , I just confirmed that the latest pre-release  https://github.com/kiwibrowser/src.next/releases/tag/2189821677 has this specific issue resolved. 👍 

~Ibuprophen

**Comment by drc5521** [comment] 2022-04-20 04:02
> @drc5521 , I just confirmed that the latest pre-release https://github.com/kiwibrowser/src.next/releases/tag/2189821677 has this specific issue resolved. +1
> 
> ~Ibuprophen
Hi, I installed the latest version and the problem has been fixed. Thank you. I will close this issue.

**Comment by drc5521** [comment] 2022-04-20 04:03
> @drc5521 , I just confirmed that the latest pre-release https://github.com/kiwibrowser/src.next/releases/tag/2189821677 has this specific issue resolved. +1
> 
> ~Ibuprophen

Hi, I installed the latest version and the problem has been fixed. Thank you. I will close this issue.

**Closed** 2022-04-20 04:03 UTC
Labels: bug
