### ISSUE TITLE
Unable to hide toolbar

### ISSUE THREAD

**Issue by CarlCD** [kiwibrowser/src.next#377] opened 2021-09-07 04:59 UTC
**Describe the bug**
Already turned off Toolbar always on screen but toolbar still there

**To Reproduce**
Turned off Tolbar always on screen on Accessibility 

**Expected behavior**
Toolbar will disappear while scrolling 

**Screenshots**

https://user-images.githubusercontent.com/40827115/132286677-ee964965-a5fe-4008-aae7-ec450bc6f6cb.mp4

**Smartphone (please complete the following information):**
 - Device: [Samsung S21 Ultra 5G]
 - Android Version : [11, OneUi 3.1]
 - Kiwi Browser Version [93.0.4577.52] com.kiwibrowser.browser-1181850297-arm64-github.apk

**Additional context**
Minor problems, no rush. Thank for the great app

**Comment by MmyGgithubAaccount** [comment] 2021-09-07 10:39
Duplicate of #182

**Closed** 2021-09-17 22:24 UTC
Labels: bug
