### ISSUE TITLE
A small window for options of extensions?

### ISSUE THREAD

**Issue by rainfall-breeze** [kiwibrowser/src.next#630] opened 2022-06-09 10:25 UTC
When the option of extensions is opened, could it pop from the bottom instead of a new tab?
Just like the lemur browser and rains browser.
![QtScrcpy_20220609_181742_452](https://user-images.githubusercontent.com/67453066/172825841-194eb6dd-5061-421e-bb25-b6dc79b0cdac.png)
![微信图片_20220609181824](https://user-images.githubusercontent.com/67453066/172825861-9591890d-de32-4015-a0a4-05cde512414f.jpg)

**Comment by d3ward** [comment] 2022-06-10 19:56
Duplicate of https://github.com/kiwibrowser/src.next/issues/479 .

**Closed by d3ward** 2022-06-10 19:56 UTC
Labels: enhancement

**Comment by Ibuprophen** [comment] 2022-07-05 21:25
@kyoyacchi, If your referring to the Kiwi Browser, the following link provides guidance to your question. 

https://github.com/kiwibrowser/src.next#releases

~Ibuprophen
