### ISSUE TITLE
Unable to undo operations when tabs are deleted

### ISSUE THREAD

**Issue by s1710335** [kiwibrowser/src.next#183] opened 2021-07-25 07:30 UTC
The "Undo" bar that appears at the bottom of the screen when you delete a tab is no longer displayed.

**Comment by Lartsch** [comment] 2021-07-25 10:32
Which tab view are you using? I'm using the grid layout and still get the "Undo" bar

**Comment by Lartsch** [comment] 2021-07-25 10:35
Also, this is a duplicate of #179 . Please add your comment there and close this issue @s1710335

**Closed** 2021-07-25 10:52 UTC
