### ISSUE TITLE
[Bug] Tabs changes its order 

### ISSUE THREAD

**Issue by joelocandol** [kiwibrowser/src.next#213] opened 2021-07-28 02:13 UTC
Idk if this problem just happen with grid tabs active, but, when I change between tabs with the slide gesture on the bottom search bar, the tabs changes its order, but if a open the tab switcher, these appear in the correct order that they were opened.

And, other little problem is that the menu that appears when you select a text (copy, past, etc). Appears above the text that you selected, so it complicated select more text

**Comment by d3ward** [comment] 2021-07-31 14:35
It's this bug still there with latest build ? 
What version you use ?
What layout of tab switcher you have ?

For the text popup #190

**Comment by joelocandol** [comment] 2021-07-31 21:28
I'm currently in the version 93.0.4577.18, last build that appears on Google play and utilize the grid layout for the tabs. I gonna prove the last GitHub build to if it's fixed

**Comment by joelocandol** [comment] 2021-08-01 04:26
I'm updated the browser to the last build: 93.0.4577.20 and the problem still present. I think it happens after a had open more than tabs, but a i not sure cause it happens randomly but a i always have more than 5 tab opened

**Comment by MooShuOrc** [comment] 2021-08-03 08:06
I believe the poster is referring to the difference in tab order between swiping on the address bar and opening the tab switcher. This happens when a tab spawns a new tab ("open in new tab" or "about:blank"). The new tab is created next to the current tab, but the tab switcher shows the new tab at the end of the list.
It's been this way for a while, and is still there as of 93.0.4577.20. It's not just the grid layout either.

**Comment by MooShuOrc** [comment] 2021-08-08 01:21
I just noticed something interesting:
I had several tabs out of order, opened the tab switcher (Horizontal [old] style, if it matters), closed a tab by swiping it down, then immediately hit undo and the tab reappeared, but now in the correct order.
I'm not sure what to make of it, but perhaps it'll help the devs figure out what's wrong.

**Comment by kiwibrowser** [comment] 2021-08-08 01:36
It's very interesting information, because it would mean that the issue is not during storage, but rather during display of the tabs

**Comment by MooShuOrc** [comment] 2021-09-20 15:35
Update: This seems to be fixed (at least for me) on the recent update to version 94.0.4606.54.
Thanks!

**Comment by d3ward** [comment] 2021-09-28 10:07
@joelocandol do you still have that problem ?

**Comment by MooShuOrc** [comment] 2021-10-02 10:24
Update: It's not as fixed as I thought. 
While checking to see if [#253](https://github.com/kiwibrowser/src.next/issues/253) is fixed (it's not), I discovered that the tabs-out-of-order problem only affects certain tab switchers. The horizontal (old) tab switcher works properly. The "original" (old vertical) does not.
Surely this wealth of info will help our wise devs figure out how to fix it. 😃

**Comment by karl-pae** [comment] 2022-03-16 14:32
Hi, download the latest build from here:
https://github.com/kiwibrowser/src.next/releases

and revert if the issue still occurs, else you can close this issue.

**Comment by d3ward** [comment] 2023-07-21 11:02
I'm not able to reproduce that . Can check if you still have the issue with latest Kiwi v116 ?

**Comment by MooShuOrc** [comment] 2023-07-21 15:13
Just tested. It seems fixed for all tab switchers.

A13 [CalyxOS 4.11.0]
Kiwi 116.0.5845.22[2]

**Closed** 2023-08-05 14:03 UTC
Labels: bug
