### ISSUE TITLE
[FeatureRequest]Clear data on exit

### ISSUE THREAD

**Issue by edward5375** [kiwibrowser/src.next#230] opened 2021-07-30 10:29 UTC
Hey can you please implement clear data on exit feature....

**Comment by karl-pae** [comment] 2021-07-30 17:02
Duplicate of #84. 
Please close this.

**Comment by Oranko** [comment] 2021-07-30 17:10
The answer is to use auto history wipe extension
I hope that will fulfill your use case :)

**Comment by d3ward** [comment] 2021-07-31 10:41
> Duplicate of #84.
> Please close this.

thank you

**Closed by d3ward** 2021-07-31 10:41 UTC
Labels: enhancement
