### ISSUE TITLE
Manifest v2, Manifest v3

### ISSUE THREAD

**Issue by soccerboys2008** [kiwibrowser/src.next#715] opened 2022-09-19 23:29 UTC
What are the plans regarding manifest v3 adoption, and will manifest v2 still be supported

Especially for adblockers

**Comment by kiwibrowser** [comment] 2022-09-19 23:35
The plan is to keep ManifestV2 active. It's quite easy to handle (as a note: we announced it almost immediately when ManifestV3 was announced).

**Comment by Peacock365** [comment] 2022-09-21 07:49
@kiwibrowser 

Do you plan to implement Manifest V3 also (while keeping the webRequest API)? I am asking because I was trying to install a Manifest V3 extension and the Chrome Web Store marked it as incompatible with my browser. Would be fantastic if both were supported in parallel. Finally, what will you do when Google removes extensions like uBlock Origin from the Chrome Web Store? Will it be possible to install them from GitHub and update them from there as well? Thank you for your time!

**Comment by karl-pae** [comment] 2022-09-21 16:03
@Peacock365 

Using my custom manifest V3 extension with latest build. No issue.  

uBlock has already started developing V3 version: uBlock Minus. But currently not compatible with kiwi browser.

**Comment by sliceanddice9** [comment] 2022-10-01 23:51
> uBlock has already started developing V3 version: uBlock Minus. But currently not compatible with kiwi browser.

Once the UBlock Minus add-on is available for download on the Chrome Store for Google Chrome Desktop, will that also mean UBlock Minus will be available on the Chrome Store for Kiwi too?

**Comment by karl-pae** [comment] 2022-10-03 02:09
Sorry! for off-topic conversation.. GitHub needs to bring pm feature..

@sliceanddice9 

You can try that extension by downloading it from here: https://github.com/gorhill/uBlock/releases

Look for uBlock lite (re-named from uBlock Minus)

Don't know why Chrome store flags it "not compatible"

**Comment by LovecraftianGodsKiller** [comment] 2023-05-28 17:40
> > uBlock has already started developing V3 version: uBlock Minus. But currently not compatible with kiwi browser.
> 
> Once the UBlock Minus add-on is available for download on the Chrome Store for Google Chrome Desktop, will that also mean UBlock Minus will be available on the Chrome Store for Kiwi on Mobile too?

I know this is like 9 months late but (just in case) the developer of ublock origin recently released the first release of the lite version of the extension and is still releasing the normal version as a zip file for chromium browsers.

**Comment by d3ward** [comment] 2023-07-02 10:22
Confirmed that Kiwi will support both MV2 and MV3 .

**Closed by d3ward** 2023-07-02 10:22 UTC

**Comment by jesus2099** [comment] 2024-09-10 18:49
Today, @Violentmonkey stopped working completely in @KiwiBrowser 124.0.6327.4, even if _developer mode_ is activated in _Extensions_ page.

https://community.metabrainz.org/t/user-scripts-on-mobile/134406/27?u=jesus2099
https://github.com/violentmonkey/violentmonkey/issues/1934

**Comment by jesus2099** [comment] 2024-09-10 20:25
Ah, sorry it's because of https://github.com/violentmonkey/violentmonkey/issues/2180 not because of Kiwi Manifest v3!
