### ISSUE TITLE
Bug after come back to the browser from recent apps 

### ISSUE THREAD

**Issue by joelocandol** [kiwibrowser/src.next#215] opened 2021-07-28 04:57 UTC
The bottom search bar doubles itself and overlapped about each other. After s while, the problem fix itself and in the meantime that it's occurring, it don't interfere with the use of the app, but a still reporting it cause it make the browser seems unstable
![Screenshot_20210727-234814](https://user-images.githubusercontent.com/59028737/127266129-f36ff8a6-b914-4a45-a798-4143a737c565.png)

Android 7.0

**Comment by joelocandol** [comment] 2021-07-28 16:15
I noticed that the problem happens when the "no internet connection" warning is showing up

**Comment by samlux04** [comment] 2021-07-31 10:38
I also got this "No internet connection" status stuck at top. When swipe the toolbar the toolbar turned green.

**Comment by joelocandol** [comment] 2021-07-31 21:31
The green toolbar also happens to me, but it fixed itself after I get back the internet connection

**Comment by Lartsch** [comment] 2021-08-01 10:17
Duplicate of #60. Please close this issue @joelocandol

**Closed** 2021-08-01 16:23 UTC
