### ISSUE TITLE
93.0.4577.7 BUG,Click response position is not correct.

### ISSUE THREAD

**Issue by luzhenhua** [kiwibrowser/src.next#83] opened 2021-07-23 09:01 UTC
https://imgtu.com/i/WsGec6
GIF demo

I am still using yandex Browser at the same time.
yandex Browser does not have this problem.
www.ithome.com/0/564/779.htm demo site
After testing multiple sites and scripts, the bottom position in the gif does not respond correctly.

**Comment by luzhenhua** [comment] 2021-07-23 09:19
I tested multiple sites again.
Sites with feature options at the bottom have this problem, sites without feature options at the bottom have no problem.
However, testing the same sites in yandex Browser did not show this problem and the click response was correct.
I am not a developer and cannot determine the reason for this.

**Comment by luzhenhua** [comment] 2021-07-23 09:27
https://imgtu.com/i/WsTqQs
twitter test

https://imgtu.com/i/Ws7PSJ
youtube test

https://imgtu.com/i/Ws7Vw6
ltaaa.com test

**Comment by KaKi87** [comment] 2021-07-23 10:20
I can reproduce this issue, which seem to only happen when address bar is positioned at bottom.

**Comment by Lartsch** [comment] 2021-07-23 10:44
Possible duplicate of #89

**Comment by KaKi87** [comment] 2021-07-23 11:20
> Possible duplicate of #89

Correct. Closing in favor of above-mentioned issue.

**Closed by KaKi87** 2021-07-23 11:20 UTC
Labels: bug
