### ISSUE TITLE
Can't select tabs group item on bottom toolbar. It select whatever behind it instead.

### ISSUE THREAD

**Issue by samlux04** [kiwibrowser/src.next#205] opened 2021-07-26 22:09 UTC
Groups item can't be selected when the toolbar at the bottom. It select whatever behind it instead (pass-through).

**Comment by Lartsch** [comment] 2021-07-26 23:01
Duplicate of #115. Please close @samlux04 and look for existing issues before posting.

**Closed** 2021-07-27 09:32 UTC
