### ISSUE TITLE
Bitwarden, autofill is broken

### ISSUE THREAD

**Issue by PerNorrman** [kiwibrowser/src.next#247] opened 2021-08-02 12:19 UTC
The autofill function for Bitwarden does not work anymore.
It always worked in old Kiwi (v 77), and has on and off also worked in the new Kiwi, but doesn't since approx.10 days.

**Comment by PerNorrman** [comment] 2021-08-02 20:35
#

**Comment by Lartsch** [comment] 2021-08-02 21:27
Duplicate off #64. Please close @PerNorrman

**Closed** 2021-08-02 22:37 UTC
