### ISSUE TITLE
ublock origin dialog is blank in private window

### ISSUE THREAD

**Issue by tortino** [kiwibrowser/src.next#374] opened 2021-09-04 18:08 UTC
**Describe the bug**
I want to open the ublock window to use the element picker, when I have loaded a page in private mode.
When I try the dialog opens but is completely blank.

**To Reproduce**
I installed ublock origin, and enabled the option to work in private windows.
then I loaded a page in private tab, and selected the ublock extension in the menu.

**Expected behavior**
The dialog of ublock origin should have opened (the onw with the element chooser and some other infos)
Instead the page was opened but it was completely blank.
(if I try the same in firefox fenix it works as expected).
the url of the blank page was:
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/popup-fenix.html

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 7]
 - Android Version : [e.g. A11 ]
 - Kiwi Browser Version [ e.g. 90.0.4577.17 ]

**Additional context**

**Comment by tortino** [comment] 2021-09-04 18:34
sorry forgot these infos:
samsung a50
android 11
kiwi version: v93.0.4577.52

**Comment by karl-pae** [comment] 2021-09-05 07:00
Yes, same occurs with me too in the latest build.
The current workaround I found was that, turning off and on the "Allow in incognito" fixes the issue. The extension will open the pop-up and can fully use its functions. 

May be this can help dev, find and fix the bug.

**Comment by Iey4iej3** [comment] 2021-09-10 11:02
Same on Lineage OS 18.1 with Kiwi Browser 93.0.4577.39.

Re-enabling uBO works until closing the incognito mode, and one needs to do this again and again so it is not a good workaround.

**Comment by kryptobolt200528** [comment] 2021-09-13 11:28
This issue happens with me too

**Comment by karl-pae** [comment] 2021-09-16 11:49
Duplicate of #289 

Close. 🙂

**Closed** 2021-09-17 22:27 UTC
Labels: bug
