### ISSUE TITLE
Rounded square app icon

### ISSUE THREAD

**Issue by NoahELE** [kiwibrowser/src.next#66] opened 2021-07-21 16:31 UTC
Please change back to the former rounded square icon.

**Comment by gitdebpro** [comment] 2021-07-23 08:39
> Please change back to the former rounded square icon.

I also demand this make the icon adaptive.

**Comment by Lartsch** [comment] 2021-07-23 16:25
Duplicate of #40. Please close.

**Closed** 2021-07-24 00:42 UTC
