### ISSUE TITLE
In offline mode shows double bottom bar & Green tint on address bar

### ISSUE THREAD

**Issue by farhanspace** [kiwibrowser/src.next#347] opened 2021-08-18 20:29 UTC
## **Describe the bug**
 These issue only occurs when "no internet connection" shows on top
 **_Double Bottom address bar_** 
 show an extra address bar under the main bottom address bar. Top address bar don't have the issue.
 **_Green tint address bar_**
 while changing tab using address bar with gesture either from left or right green tint show over the address bar. Top and bottom address bar the green tint shown in both of  them.

## **To Reproduce**

 **_Double Bottom address bar_**
 1. Fully load any webpage
 2. Turn off your internet connection 
 3. In few seconds extra bottom bar shows

**_Green tint address bar_**
1. No internet connection
2. Try to change tab with left or right address bar gesture

## **Expected behavior**
No extra bottom address bar & no green tint while changing tab

## **Screenshots**
![Screenshot_20210819-013021281](https://user-images.githubusercontent.com/62940848/129964786-59328e19-1022-4808-9b36-c89382bed7a2.jpg)

![Screenshot_20210819-013032500](https://user-images.githubusercontent.com/62940848/129964818-92e72943-b02c-4491-9053-e137830666ab.jpg)

## **Smartphone:**
 - Device: [OnePlus 6t]
 - Android Version : [A10]
 - Kiwi Browser Version [ 93.0.4577.39 ]

**Comment by karl-pae** [comment] 2022-03-20 09:57
Hi, download the latest build from here:
https://github.com/kiwibrowser/src.next/releases

I am unable to reproduce any of the above two issues, revert if the issue still occurs, else you can close this issue.

**Closed** 2022-03-31 18:45 UTC
Labels: bug
