### ISSUE TITLE
Latest version issue

### ISSUE THREAD

**Issue by abc-happy** [kiwibrowser/src.next#73] opened 2021-07-22 21:01 UTC
Open the bottom toolbar. All pop-up plugins cannot be used normally. The address bar cannot be automatically hidden when browsing the web. I hope the author can improve it. My Samsung model note9

**Comment by Lartsch** [comment] 2021-07-23 11:30
Could further elaborate on this issue? @abc-happy At least I could not really tell what the issue is by your description.

In general, I think Kiwi's developers can only give limited support for extensions. Some issues can only be fixed by the extension devs. Also, some extensions will probably never work with mobile chromium browsers.

**Comment by karl-pae** [comment] 2021-08-02 10:48
Not properly explained. @d3ward should this be closed ?

**Comment by d3ward** [comment] 2021-08-02 11:01
> Not properly explained. @d3ward should this be closed ?
Yes.

@abc-happy please check latest update and if needed make a new issue with the bug template and detailed info

**Closed by d3ward** 2021-08-02 11:01 UTC
