### ISSUE TITLE
Add backup feature like as in Soul Browser.

### ISSUE THREAD

**Issue by kyoyacchi** [kiwibrowser/src.next#404] opened 2021-09-29 19:01 UTC
It would be really good to backup our settings to device and restore it, right?

Like this

![Screenshot_2021-09-29-21-59-25](https://user-images.githubusercontent.com/63583961/135332021-db13b1a0-0778-43dd-bda9-97299c2b8b42.png)
![Screenshot_2021-09-29-21-59-29](https://user-images.githubusercontent.com/63583961/135332025-a063fb2a-025a-4352-8e48-26136e640c96.png)

**Comment by KaKi87** [comment] 2021-09-30 10:59
Duplicate of #122

**Closed by KaKi87** 2021-09-30 10:59 UTC
Labels: enhancement

**Comment by kyoyacchi** [comment] 2021-10-01 20:54
> Duplicate of #122

What makes you think that this issue is "duplicate"?

**Comment by KaKi87** [comment] 2021-10-02 08:40
Because it's the same feature request.
