### ISSUE TITLE
Bottom bar glitch

### ISSUE THREAD

**Issue by Killerpac** [kiwibrowser/src.next#240] opened 2021-08-01 03:45 UTC
**Describe the bug**
When the browser goes offline for some reason the bottom bar glitches

**To Reproduce**
Turn off the internet when browsing and search search something.

**Expected behavior**
No glitching

**Screenshots**
![Screenshot_20210801-091116.png](https://user-images.githubusercontent.com/45239423/127758474-4bdb400d-b3ee-4688-a431-cb0cc4c1f688.png)

**Smartphone (please complete the following information):**
 - Device : Moto E4 Plus
 - Android Version : A7 
 - Kiwi Browser Version : version 93

**Comment by Lartsch** [comment] 2021-08-01 10:07
Duplicate of #60. Please close this issue @Killerpac

**Closed** 2021-08-01 10:08 UTC
Labels: bug
