### ISSUE TITLE
Change download location and block auto download don't work in latest version

### ISSUE THREAD

**Issue by Doc-4** [kiwibrowser/src.next#236] opened 2021-07-28 04:18 UTC
Attempting to stop auto downloads in site settings or changing any download-related settings doesn't seem to make a difference, files still get downloaded to the default downloads location and you're never prompted in this process regardless of any setting combination I tested, and pressing on the download location under site settings provides no option to change it.

**Comment by Lartsch** [comment] 2021-08-01 10:20
Duplicate of #68. Please close this issue @Doc-4

**Closed** 2021-08-01 15:47 UTC
