### ISSUE TITLE
Show extensions first - doesn't show any extensions

### ISSUE THREAD

**Issue by fredgolightly** [kiwibrowser/src.next#470] opened 2022-01-04 10:52 UTC
I use umatrix & ubo, but the accessibility option to show extensions first in the menu causes them to disappear from the menu entirely. This is new in chrome 98 for me

**Comment by kiwibrowser** [comment] 2022-01-04 12:51
I couldn't reproduce the issue, can you share a screenshot  ?
![Screenshot_20220104-145055](https://user-images.githubusercontent.com/40272275/148061766-a3334ffa-c6ce-4bea-b2de-49b028cbdb9d.jpg)

**Comment by fredgolightly** [comment] 2022-01-04 13:02
Here's a screen recording turning it on on my Tab S7: [https://easyupload.io/oi3qod](url)

**Comment by eliospeed** [comment] 2022-01-05 10:20
I think this issue is reproduced on large screens only. I don't have the extensions when i use kiwi on full screen but when i use split screen i can see them. Thanks

**Comment by babaolanqiu** [comment] 2022-01-07 09:17
I'm facing the same problem on Tab S7, and it appears exactly like @eliospeed described above.

**Comment by Mav3r1x** [comment] 2022-01-09 02:45
Can confirm I have the same issue on my tab s5e. On phone, the extensions show properly.

**Comment by kiwibrowser** [comment] 2022-01-09 03:08
It's clearly an issue on tablets only and will be resolved in one or two builds (so likely tomorrow).
The workaround is to disable "Show extensions first"

When the "Show extensions first" option is checked, then the extension is added after displaying the "Star, Refresh, Download" bar.

However, on tablet this bar doesn't exist so I'll change the logic for tablets and push the build.

**Comment by kiwibrowser** [comment] 2022-01-09 05:11
Fixed.

**Closed by kiwibrowser** 2022-01-09 05:11 UTC
