### ISSUE TITLE
Long press text selection pop up cover the selection area

### ISSUE THREAD

**Issue by hermit-0** [kiwibrowser/src.next#180] opened 2021-07-25 06:05 UTC
Long press text selection pop up cover the selected text. Can't interact with the selection, the pop up cover the selection area. Sometimes it works sometimes it doesn't.

![Screenshot_20210725-115727595](https://user-images.githubusercontent.com/62940848/126889399-b78e5d27-e2af-4f77-a984-414b00264ca4.jpg)

![Screenshot_20210725-115734757](https://user-images.githubusercontent.com/62940848/126889413-a3e270a6-1498-4baf-8349-b1e84e0e8a7f.jpg)

**Comment by Lartsch** [comment] 2021-07-25 11:48
Duplicate of #170. Please close and add your comment over there. @hermit-0

**Closed** 2021-07-25 15:23 UTC
